lib/cloak/ciphers/aes_ctr.ex

It is a good practice to store keys, secret tokens in the environment variables. Then they are never committed into repository, and this is de facto standard in environments such as Heroku.
This PR adds possibility to define that keys are stored in the environment using  `{:system, something}` syntax that is often used by the Phoenix Framework.

Added ability to store keys in the environment variables

---

README.md
lib/cloak.ex
lib/cloak/ciphers/behaviour.ex

This is needed in order to prepare the users for the upcoming Ecto version 2.0, and because the Cloak.Model was removed.
Related commit: https://github.com/danielberkompas/cloak/commit/431289bc52546edc324e3a643ce42d7a6c5bbd6f

Update examples to reflect the remotion of Cloak.Model

---

config/test.exs
lib/cloak/ciphers/aes_ctr.ex
test/cloak/ciphers/aes_ctr_test.exs

This is needed because the user will probably store the keys encoded as base64 when using environment variables.
This also adds a basic error report when the expected key is missing or is not a valid base64 string.
Closes #9

Decode AES environment variable keys from base64

---

lib/mix/tasks/cloak.migrate.ex

`validate!` was never working because when the data was valid, there was
no matching function clause. Added an empty clause for the valid case.

Fix validation bug in cloak.migrate

---

lib/cloak.ex
lib/cloak/ciphers/aes_ctr.ex
lib/cloak/config.ex
lib/ecto/encrypted_field.ex

This will prevent Cloak from needing to be recompiled when you change
keys.

Rely on configuration at runtime

---

lib/ecto/sha_256_field.ex

A similar strategy worked for me in querying a hashed field for identifying users by email address while keeping email addresses encrypted.  I'm happy to make changes if this isn't idiomatic.

Add `prepare_changes` example to module doc for use with ecto 2.0

---

lib/cloak.ex
lib/cloak/ciphers/aes_ctr.ex
lib/cloak/ciphers/behaviour.ex
lib/cloak/config.ex
mix.exs
test/cloak_test.exs
test/mix/cloak.migrate_test.exs

I've cleaned up the various compile warnings in Cloak under Elixir 1.4.
The biggest change was to lib/cloak/ciphers.behaviour.ex, where I switched it from the deprecated "use Behaviour" to using @callback definitions. This doesn't change any behaviour.

clean up compile warnings under Elixir 1.4

---

lib/cloak.ex
lib/cloak/ciphers/aes_ctr.ex
lib/cloak/ciphers/util.ex
lib/cloak/config.ex
lib/cloak/util.ex
test/cloak_test.exs

This resolves #36.
Adds:
- `Cloak.Ciphers.Util` for dealing with generic key fetch operations from configs.
- Ability to use multiple ciphers with various tags. Previously would only encrypt with default cipher.
- Add tests surrounding new behavior
- Update docs
- Fix `decrypt/1` to no longer fail if the first cipher was not the matching cipher for the ciphertext.
- Add typespecs in a bunch of places
Let me know if there's anything else you need out of this! I'm going to be bringing these changes into a project, so I will get some real world testing into the mix, too.

Allow multiple concurrent ciphers to encrypt

---

config/test.exs
lib/cloak/ciphers/aes_gcm.ex
lib/cloak/tags/decoder.ex
lib/cloak/tags/encoder.ex
test/cloak/ciphers/aes_gcm_test.exs
test/cloak/tags/decoder_test.exs
test/cloak/tags/encoder_test.exs

This PR adds the AESGCM block cipher which I think could eventually be the default cipher that should ship with Cloak. This form of encryption provides confidentiality, integrity and authenticity assurances on the data that CTR does not provide. The API should be exactly the same as CTR.
In addition I've added arbitrary length tagging instead of hard coding 1 bit for the tag value. This allows to keep more than 255 keys simultaneously for a single cipher. (future proofing) Let me know if you have any questions regarding the implementation or want me to add more context or change anything.

[#33] Add galois counter mode cipher

---

lib/cloak/types/encrypted_integer_array_field.ex
lib/cloak/types/encrypted_string_array_field.ex
test/cloak/types/encrypted_integer_array_field_test.exs
test/cloak/types/encrypted_string_array_field_test.exs

Had a need to encrypt an array of strings (a supported Ecto type) in the db. Example use case is a list of permissions in a record. This used to work in Cloak version 0.3 by using the EncryptedMapField because it was simply running the data through Json without actually casting into Ecto. Newer versions cloak do more type checking, so the Ecto type {:array, :string} fails now.
This PR creates two new encrypted field types corresponding to the Ecto types of {:array, :string} and {:array, :integer}. They are simple variations of the existing Map type. Docs and tests for both have been added/updated.
Now formatted...

Add support for encrypted Ecto String and Integer Array types

---

lib/cloak.ex

First of all, thanks for creating this library ❤️ 
This PR fixes a small typo I found in the documentation for the `Cloak` module.
If there are any additional contribution steps I need to follow, please let me know!

[Documentation] Fix small typo: SHA265 -> SHA256

---

lib/cloak/field.ex
lib/cloak/fields/binary.ex
test/cloak/fields/binary_test.exs

We want to be sure that nils will be properly casted, dumped, and loaded
as nils, rather than converted to empty strings.

Improve nil support in Ecto types

---

lib/cloak/fields/pbkdf2.ex
mix.exs
mix.lock
test/cloak/fields/pbkdf2_test.exs

For very sensitive information (Social Security numbers, tax identification numbers, or other ostensibly unique numbers assigned to people), it is a good idea to use a key stretching algorithm for the blind index to make it harder to brute force the hashed values. PBKDF2 is a key stretching algorithm that accomplishes this.

Add support for PBKDF2 for blind indexing

---

lib/cloak/migrator.ex

Dear Daniel, thank you for this library. I have modified the migration code to not fail in case a schema is mapped on an empty table.

Do not fail migration task when running on schema linked to empty table

---

README.md

In order to decrease surprise to others updating to 0.7.x from older version of Cloak, I've added a link to the readme.
Please let me know if there are better placements/wording for this.

Add a link to the 0.6.x to 0.7.x migration guide to readme

---

.travis.yml
lib/cloak/migrator.ex
test/cloak/migrator_test.exs
test/support/comment.ex
test/support/migrations/20180915035851_create_posts.exs
test/support/post.ex

The migrator will no longer fail if your schema contains embedded
schemas, so this fixes #81.
However, Cloak fields will not encrypt in embedded schemas,
because Ecto does not call `dump` callbacks on custom Ecto types in
embedded schemas. I'm going to add an issue to investigate further.

[#81] Fix migrator with embedded schemas

---

lib/cloak/migrator.ex
test/cloak/migrator_test.exs

This functionality appears to have been introduced in
cdeae97c69f7c54aeadf0921db30dc411d7a9938; however, it looks like it was
removed as part of the refactor to use a cursor for IDs rather than
requiring numeric IDs in 01946dcd39fe96be9b79c1d095fc71ec311cfd93.
With this change, if the migrator is passed a schema that is linked to
an empty table, an error is no longer raised. Instead, the migration is
not attempted, and the function returns that the migration completed.
This does have the impact of changing the return value of the function
in this scenario. Rather than the `:ok` it otherwise returns, instead
it returns a tuple `{:ok, message}`, where the message includes
information about why no migration took place. It doesn't appear that
the return value of this function is used; …

Migration task succeeds on empty table

---

README.md
config/test.exs
guides/how_to/install.md
guides/upgrading/0.6.x_to_0.7.x.md
guides/upgrading/0.8.x_to_0.9.x.md
lib/cloak/ciphers/aes_ctr.ex
lib/cloak/ciphers/aes_gcm.ex
test/cloak/ciphers/aes_gcm_test.exs

This allows you to set a 12-byte IV as mentioned in #93, like so:
```elixir
config :my_app, MyApp.Vault,
ciphers: [
default: {
Cloak.Ciphers.AES.GCM,
tag: "AES.GCM.V1",
key: Base.decode64!("your-key-here"),
iv_length: 12
}
]
```
In Cloak 2.0, one of the breaking changes will be to make `iv_length`
default to `12` instead of the current `16`.

[#93] Add option to specify iv length for AES.GCM

---

README.md

This changes the link to the hex.pm documentation on how to upgrade from
0.9.x to 1.0.x.

Update Upgrade Documentation Link

---

README.md
lib/cloak/ciphers/aes_ctr.ex
lib/cloak/ciphers/aes_gcm.ex
lib/cloak/ciphers/deprecated/aes_ctr.ex
lib/cloak/ciphers/deprecated/aes_gcm.ex
lib/cloak/crypto.ex
lib/cloak/crypto/interface.ex
test/cloak/ciphers/deprecated/aes_ctr_test.exs
test/cloak/ciphers/deprecated/aes_gcm_test.exs

Hi, this PR is not 100% done, but I believe it's a step in the right direction.
I have created a Cloak.Crypto module to intercept the calls to crypto and change based on `System.otp_release/0`
I have created a Cloak.Crypto.Interface behavior to ensure the functions across erlang versions.
There are a couple of things still broken mainly because I am a little out of my depth in the knowledge of ciphers in general.
First, the only version this seems to partially work on is erlang 24 and up. I don't know why but when I set the erlang version to anything less than 24 (i.e. 22  & 23), it gives me an 'Unknown Cipher' error even though the API should be the same.
Second, I am having trouble getting the AES.GCM functions to encrypt properly on erlang 24. I am missing something with the contract …

Erlang 24 Support

---

mix.exs
mix.lock

This dependency is used by `cloak_ecto`, not by `cloak`. So it doesn't need to be included in the Mixfile any longer.

Remove unused pbkdf2 dependency

---

guides/upgrading/0.6.x_to_0.7.x.md

I was upgrading an old project from v6 and ran into this. The example code uses `decode64` instead of `decode64!`, which returns an `{:ok, ...}` tuple and causes an error in the crypto library that had me scratching my head.
I realize it's a really old version at this point, but hopefully this will help someone out.

Fix example code for Base.decode64!

---

lib/cloak/vault.ex

I ran into a case where I wanted to return `:ignore` in my Vault `init/1` callback, but the strict match on `{:ok, pid}` was causing the supervisor to crash.

Allow vault gen server to return other responses

---

guides/cheatsheets/cheatsheet.cheatmd

Configuration requires the `ciphers` key to be a keyword list of `key: {CipherModule, opts}`

Update cheatsheet to fix mix config

---

CHANGELOG.md
LICENSE.md
README.md
mix.exs

Besides other documentation changes, this commit includes all relevant
documents to the generated HTML doc for HexDocs.pm and leverages on
latest features of ExDoc.

Misc doc changes

---

lib/cloak/exceptions/vault_not_started.ex
lib/cloak/vault.ex
test/cloak/vault_test.exs

Fixes #125. The problem was that users weren't waiting for the vault process to start before calling functions on it in their `release.ex` file.

Raise helpful error if vault hasn't been started
